"""KRIC Open API의 역·노선·시간표·편의시설 client를 제공한다."""

from .client import KricClient
from .files import (
    NATIONWIDE_STATION_INFO_DATASET_ID,
    STATION_CODE_FILE_ID,
    STATION_CODE_NOTICE_ID,
    KricFileClient,
    parse_xlsx_table,
    parse_nationwide_station_info_xlsx,
    parse_station_code_xlsx,
)
from .maritime import DataGoKrMaritimeClient
from .port_guidelines import PORT_GUIDELINE_SOURCE_ID, PortGuidelineFileClient, parse_port_guideline_locations
from .storage import RustfsObjectStore, StoredObject
from .exceptions import (
    KricAuthError,
    KricError,
    KricInvalidParameterError,
    KricNetworkError,
    KricRateLimitError,
    KricServerError,
    KricStorageConfigurationError,
)
from .models import (
    ServiceDayCode,
    FileStationInfo,
    StationCodeInfo,
    CoastalFerrySchedule,
    DomesticFerryPort,
    PortGuidelineLocation,
    DomesticShipOperation,
    FerryShipType,
    FerryTerminal,
    KricFileDownload,
    KricFileTable,
    StationFacility,
    StationInfo,
    StationTimetableEntry,
    SubwayRouteStop,
    SubwayTimetableEntry,
)

__all__ = [
    "KricAuthError",
    "KricClient",
    "DataGoKrMaritimeClient",
    "PortGuidelineFileClient",
    "KricFileClient",
    "RustfsObjectStore",
    "StoredObject",
    "KricError",
    "KricInvalidParameterError",
    "KricNetworkError",
    "KricRateLimitError",
    "KricServerError",
    "KricStorageConfigurationError",
    "ServiceDayCode",
    "FileStationInfo",
    "StationCodeInfo",
    "CoastalFerrySchedule",
    "DomesticFerryPort",
    "PortGuidelineLocation",
    "DomesticShipOperation",
    "FerryShipType",
    "FerryTerminal",
    "KricFileDownload",
    "KricFileTable",
    "NATIONWIDE_STATION_INFO_DATASET_ID",
    "STATION_CODE_NOTICE_ID",
    "STATION_CODE_FILE_ID",
    "PORT_GUIDELINE_SOURCE_ID",
    "parse_port_guideline_locations",
    "parse_nationwide_station_info_xlsx",
    "parse_station_code_xlsx",
    "parse_xlsx_table",
    "StationFacility",
    "StationInfo",
    "StationTimetableEntry",
    "SubwayRouteStop",
    "SubwayTimetableEntry",
]
